### ISSUE TITLE
Fancy updating this?

### ISSUE THREAD

**Issue by bfeist** [marquizzo/three.ts-template#1]
Lots of broken dependencies and ts errors when trying to use this now.

**Comment by marquizzo** [comment]
Updated to Three.js r140, Webpack 5, & latest Typescript on the following commits:

https://github.com/marquizzo/three.ts-template/commit/d2dc9d10edeecb8090529a9f6ae095bc30a4ff2e
https://github.com/marquizzo/three.ts-template/commit/9770973bfcde25ec23cd7590c9628f8b6221d775
